### ISSUE TITLE
Add Search app

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/SampleWebsiteTheme#1]
Similarly to how Images (logo) and Launchpad are added to the top bar of the Desktop Surface, add the search input to the top bar.

**Comment by habib535** [comment]
We needs to have more generic Blending points in the Website Themes. The idea is inspired based on the comments from https://github.com/StarcounterApps/SampleWebsiteTheme/pull/2

**Comment by PatrykSzwer** [comment]
Since #2 is merged, can This issue be closed?

**Comment by habib535** [comment]
Closing is done.
