### ISSUE TITLE
`::slotted smth` is not a valid selector

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/SampleWebsiteTheme#9]
It seems https://github.com/StarcounterApps/SampleWebsiteTheme/pull/7 introduced a lot of invalid selectors
`::slotted a, ::slotted > starcounter-include > juicy-composition,` are not valid CSS selectors

**Comment by Mihaiii** [comment]
Closing as done.

**Comment by tomalec** [comment]
`::slotted(starcounter-include > juicy-composition > *)` is still not a valid CSS selector

**Comment by PatrykSzwer** [comment]
Since PR #11 is done, can this be closed?

**Comment by Mihaiii** [comment]
Closing as done.
